// Account action types
export const ACCOUNT_EDIT_EMAIL = 'ACCOUNT_EDIT_EMAIL'
export const ACCOUNT_EDIT_NAME = 'ACCOUNT_EDIT_NAME'
export const ACCOUNT_EDIT_PROFILE_PICTURE = 'ACCOUNT_EDIT_PROFILE_PICTURE'
export const ACCOUNT_CLEAR = 'ACCOUNT_CLEAR'
